# @package _global_

defaults:
  - /habitat: habitat_config_base

  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgb_head_agent
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: fetch_no_wheels

  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - arm_action

  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  task:
    # No task logic, empty task
    type: RearrangeEmptyTask-v0
    actions:
      arm_action:
        grip_controller: "MagicGraspAction"
  environment:
    # Endless episode
    max_episode_steps: 0
  simulator:
    type: RearrangeSim-v0
    seed: 100
    ############################
    # Benchmark relevant settings
    ############################
    concur_render: True
    auto_sleep: True
    ############################
    additional_object_paths:
      - "data/objects/ycb/configs/"
    agents:
      main_agent:
        sim_sensors:
          head_rgb_sensor:
            height: 128
            width: 128
        is_set_start_state: True
        start_position: [3.66997,0.0,3.5041]
        start_rotation: [0.0, 0.999657, 0.0, -0.0261769]
    habitat_sim_v0:
      enable_physics: True
  dataset:
    data_path: data/ep_datasets/bench_scene.json.gz
