# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: task_config_base
  - /habitat/dataset/rearrangement: replica_cad

  - /habitat/task/measurements:
    - pddl_success
    - num_steps
    - did_agents_collide
    - num_agents_collide
    - composite_stage_goals
    - pddl_subgoal_reward
    - rearrange_cooperate_reward

  - /habitat/task/lab_sensors:
    - relative_resting_pos_sensor
    - target_start_sensor
    - goal_sensor
    - joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - target_start_gps_compass_sensor
    - target_goal_gps_compass_sensor
    - localization_sensor
    - humanoid_joint_sensor


  # Uncomment this if you want to visualize third_rgb
  # - override /habitat/simulator/sensor_setups@habitat.simulator.agents.agent_1.sim_sensors.head_depth_sensor: third_rgb_sensor

  # For Spot observation space
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.agent_0: depth_head_agent
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.agent_1: depth_head_agent


  - _self_


habitat:
  task:
    type: RearrangePddlTask-v0
    reward_measure: rearrange_cooperate_reward
    success_measure: pddl_success
    measurements:
      pddl_success:
        must_call_stop: False

    task_spec_base_path: benchmark/multi_agent/
    task_spec: pddl/multi_agent_tidy_house
    pddl_domain_def: fp
  gym:
    obs_keys:
      - agent_0_head_depth
      - agent_0_relative_resting_position
      - agent_0_obj_start_sensor
      - agent_0_obj_goal_sensor
      - agent_0_obj_start_gps_compass
      - agent_0_obj_goal_gps_compass
      - agent_0_joint
      - agent_0_is_holding
      - agent_0_ee_pos
      - agent_0_localization_sensor
      - agent_0_other_agent_gps
      - agent_1_head_depth
      - agent_1_does_want_terminate
      - agent_0_does_want_terminate
      - agent_1_relative_resting_position
      - agent_1_obj_start_sensor
      - agent_1_obj_goal_sensor
      - agent_1_obj_start_gps_compass
      - agent_1_obj_goal_gps_compass
      - agent_1_is_holding
      - agent_1_ee_pos
      - agent_1_localization_sensor
      - agent_1_humanoid_joint_sensor
      - agent_1_other_agent_gps
  simulator:
    # Add Spot robot agents
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
    concur_render: True
    auto_sleep: True
    # Add Spot robot agents
    agents_order:
      - agent_0
      - agent_1
    agents:
      agent_0:
        radius: 0.25
        height: 1.8
        articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
        articulated_agent_type: "SpotRobot"

      agent_1:
        radius: 0.25
        height: 1.8
        articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
        articulated_agent_type: "SpotRobot"


    kinematic_mode: True
    ac_freq_ratio: 1
    step_physics: False
    habitat_sim_v0:
      allow_sliding: True
      enable_physics: True
  dataset:
    data_path: data/datasets/hssd/rearrange/{split}/social_rearrange.json.gz
