# @package habitat.simulator.agents.fetch_suction
defaults:
  - fetch@_here_
  - _self_

articulated_agent_type: FetchSuctionRobot
articulated_agent_urdf: data/robots/hab_fetch/robots/hab_suction.urdf
