# @package habitat.simulator.agents.human
defaults:
  - agent_base
  - _self_

radius: 0.3
articulated_agent_type: 'KinematicHumanoid'
articulated_agent_urdf: 'data/humanoids/humanoid_data/female_2/female_2.urdf'
motion_data_path: "data/humanoids/humanoid_data/female_2/female_2_motion_data_smplx.pkl"
sim_sensors:
  head_rgb_sensor:
    height: 224
    width: 224
  head_depth_sensor:
    height: 224
    width: 224
